name: flutter_gen_ai_chat_ui
description: A Flutter package that provides a customizable chat UI for AI applications, featuring streaming responses, code highlighting, and markdown support.
version: 1.3.0
homepage: https://github.com/hooshyar/flutter_gen_ai_chat_ui
repository: https://github.com/hooshyar/flutter_gen_ai_chat_ui
issue_tracker: https://github.com/hooshyar/flutter_gen_ai_chat_ui/issues
documentation: https://github.com/hooshyar/flutter_gen_ai_chat_ui/blob/main/README.md

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  dash_chat_2:
    git:
      url: https://github.com/Dartly/Dash-Chat-2.git
      ref: 2665dcc19a4401d6159ac477902e9778b0ae8b14
  shimmer: ^3.0.0
  google_fonts: ^6.2.1
  flutter_markdown: ^0.7.6 
  url_launcher: ^6.2.5
  intl: ^0.19.0
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
